web/router.ex
defmodule One2one.Router do
  use One2one.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", One2one do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/caller", CallerController, :index
    get "/callee", CalleeController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", One2one do
  #   pipe_through :api
  # end
end

lib/one2one/endpoint.ex
defmodule One2one.Endpoint do
  use Phoenix.Endpoint, otp_app: :one2one

  socket "/socket", One2one.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :one2one, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_one2one_key",
    signing_salt: "JhhL7f/D"

  plug One2one.Router
end

lib/one2one/repo.ex
defmodule One2one.Repo do
  use Ecto.Repo, otp_app: :one2one
end

web/controllers/callee_controller.ex
defmodule One2one.CalleeController do
    use One2one.Web, :controller

    def index(conn, _params) do
        render conn, "index.html"
    end
end

web/controllers/caller_controller.ex
defmodule One2one.CallerController do
    use One2one.Web, :controller

    def index(conn, _params) do
        render conn, "index.html"
    end
end

web/controllers/page_controller.ex
defmodule One2one.PageController do
  use One2one.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/callee_view.ex
defmodule One2one.CalleeView do
  use One2one.Web, :view
end

web/views/caller_view.ex
defmodule One2one.CallerView do
  use One2one.Web, :view
end

web/views/error_view.ex
defmodule One2one.ErrorView do
  use One2one.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule One2one.LayoutView do
  use One2one.Web, :view
end

web/views/page_view.ex
defmodule One2one.PageView do
  use One2one.Web, :view
end

web/templates/callee/index.html.eex
<h1 id="callee">CALLEE PAGE</h1>
<div class="row">
    <div class="col-sm-6 center-panel">
        <video id="remoteVideo" autoplay></video>
    </div>
</div>
<style>
video {
    width: 320px;
    height: 240px;
    background-color: black
}

.center-panel {
    text-align: center;
}

.mybtn {
    width: 100%;
    margin-bottom: 5px;
}
</style>

web/templates/caller/index.html.eex
<h1 id="caller">CALLER PAGE</h1>
<div class="row">
    <div class="col-sm-6 center-panel">
        <video id="localVideo" autoplay></video>
    </div>
    <div class="col-sm-6 center-panel">
        <button class="btn btn-danger mybtn" id="connect">Connect</button>
        <button class="btn btn-primary mybtn" id="call">Call</button>
        <button class="btn btn-success mybtn" id="hangup">Hangup</button>
    </div>
</div>
<style>
video {
    width: 320px;
    height: 240px;
    background-color: black
}

.center-panel {
    text-align: center;
}

.mybtn {
    width: 100%;
    margin-bottom: 5px;
}
</style>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>One 2 One</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="text-center">
<h1>ONE 2 ONE WEBRTC VIDEO CALL</h1>
<span class="col-lg-6"><%= link "Goto Caller Page", to: caller_path(@conn, :index), class: "btn btn-primary", style: "width: 180px" %></span>
<span class="col-lg-6"><%= link "Goto Callee Page", to: callee_path(@conn, :index), class: "btn btn-danger", style: "width: 180px" %></span>
</div>